language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kJo30zi7hfoDux0eB+8ZbIHZ4Q7HIsX73TltIb2YtrBaVZa9N3AtLA8E1y+pzXiI/ZC69YjasBLoiFgXSSJuv3FWNiuMJ7/z2n98gLKYX5Ak823vL9/tITYdyRZTO2dXqy6UYbiX1rccCBoTSoYrHe3/52WspmJkWwPPXeREBI4=
  file:
    - 'fillers.js'
    - 'fillers.min.js'
  on:
    tags: true
